### ISSUE TITLE
Make title and slug consistent

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/writing-gradle-plugins#1]
Currently the main header says "Writing Gradle Plugins", the link on https://gradle.org/docs is "Writing Gradle Plugins **in Java**" and the slug is "writing-gradle-plugins-in-java".

Let's make the title consistent everywhere. Since we currently don't cover writing plugins in other languages than Java and I don't think we decided to write such guides, I suggest we go with simply "Writing Gradle Plugins".

**Comment by ysb33r** [comment]
We discussed this with @bmuschko last week and the feeling is that we should keep the gate open for plugins in other languages. 

Personally I think we should just fix the title.

**Comment by pioterj** [comment]
The gate wouldn't be closed if we removed "in Java" from the title. I don't think that covering developing plugins in other languages will become a priority any time soon. Once it does it may not necessarily be done with other getting started guides like "Writing plugins in Groovy" or "in Kotlin". We may use a different way to tackle that like adding ability to switch the language within the guide, creating a dedicated topical guide on using Kotlin with Gradle etc.

@bmuschko WDYT?

**Comment by bmuschko** [comment]
I'd remove "in Java" for now. The guide really is about writing plugins. The language plugin authors choose to use is just syntax. The API they use is the same.

**Comment by bmuschko** [comment]
Can we just ask @chaficnajjar to fix that? "in Java" is really only used here: https://gradle.org/docs.

**Comment by chaficnajjar** [comment]
@bmuschko I'll take care of it :+1:

**Comment by bmuschko** [comment]
@chaficnajjar thx!

**Comment by chaficnajjar** [comment]
@bmuschko Done. What about the slug "writing-gradle-plugins-in-java"?

**Comment by bmuschko** [comment]
@chaficnajjar We should remove it from the slug as well.

**Comment by chaficnajjar** [comment]
@bmuschko I can edit the link in gradle.org/docs but I don't have the permissions edit the name of this repository. Can you do it @ysb33r?

- [ ] @ysb33r to edit the name of this repository to `writing-gradle-plugins`
- [ ] @chaficnajjar to edit the link in gradle.org/docs to point to guides.gradle.org/writing-gradle-plugins
- [ ] @chaficnajjar to set up the redirect link guides.gradle.org/writing-gradle-plugins-in-java -> guides.gradle.org/writing-gradle-plugins (unless Github does it automatically, but I don't think so)

**Comment by ysb33r** [comment]
I've covered all of the necessary changes with regards to the repository. @chaficnajjar you now need to take care of the PR that I created and put the redirection in place.

**Comment by chaficnajjar** [comment]
Thanks @ysb33r. I'll take care of the rest.

**Comment by chaficnajjar** [comment]
Thanks @pioterj @ysb33r @bmuschko, closing as delivered. It's worth mentioning that this issue of inconsistency also exists in other guides such as [Writing a Getting Started Guide](https://github.com/gradle-guides/writing-getting-started-guides). Let me know if you'd also like to update those guides.
