### ISSUE TITLE
Error when trying the tutorial: Could not get unknown property 'org'

### ISSUE THREAD

**Issue by etienne-sf** [gradle-guides/writing-gradle-plugins#17]
Hello,

  Thanks for all your docs.
Very complete.

But I'm stuck on the tutorial at this point:
https://guides.gradle.org/writing-gradle-plugins/#apply_the_plugin_to_the_host_project

It's on this line:

apply plugin: org.example.greeting.GreetingPlugin

I get this error:
 Could not get unknown property 'org' for root project 'graphql-gradle-plugin-project' of type org.gradle.api.Project.

If I add quotes like this:
apply plugin: 'org.example.greeting.GreetingPlugin'

But, then I get this error:
lugin with id 'org.example.greeting.GreetingPlugin' not found.

(Which is probably solved by what's following in the tutorial, but still needs quotes apparently).

**Comment by etienne-sf** [comment]
You can find the code in this tag:
https://github.com/graphql-java-generator/graphql-gradle-plugin-project/releases/tag/writing-gradle-plugins__issue_17

(just do a "gradle build")

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #290](https://github.com/gradle/guides/issues/290) via [**ZenHub**](https://www.zenhub.com/)
