### ISSUE TITLE
Greeting plugin uses buildSrc directory which cannot be published

### ISSUE THREAD

**Issue by mikemac42** [gradle-guides/writing-gradle-plugins#18]
If you develop the greeting plugin in the tutorial, you end up with a plugin that can only be used in that project (as far as I can tell).  I felt very confused when following the Next Steps links and tried to publish the plugin for use in a different project.  Eventually I found out that the buildSrc directory doesn't get picked up by the java-gradle-plugin build, so the jar was empty.

I think it would be beneficial to have note in the tutorial mentioning this limitation.  Even better would be having a tutorial for publishing the greeting plugin developed in this tutorial.

**Comment by lacasseio** [comment]
Issue moved to [gradle/guides #303](https://github.com/gradle/guides/issues/303) via [**ZenHub**](https://www.zenhub.com/)
