### ISSUE TITLE
Javadocs link is not working

### ISSUE THREAD

**Issue by pioterj** [gradle-guides/writing-gradle-plugins#3]
The javadocs link is not working in the following fragment:

> Use the Gradle DSL Reference and {javadocs}[Javadocs] to learn what you can do with the Gradle API. Start with the entry for Project. You can find out more about what you can achieve by also following the links in Next steps.

**Comment by bmuschko** [comment]
+1 needs to be fixed

**Comment by ysb33r** [comment]
Done. Fixed by #2.
