### ISSUE TITLE
JDK requirements has been changed to 1.7 but uses 1.8 syntax

### ISSUE THREAD

**Issue by bmuschko** [gradle-guides/writing-gradle-plugins#4]
The following source code example still uses 1.8 syntax.

https://guides.gradle.org/writing-gradle-plugins/#create_the_plugin

**Comment by ysb33r** [comment]
Which line of code?

**Comment by bmuschko** [comment]
`project.getTasks().create("hello", Greeting.class, (task) -> {`

**Comment by eriwen** [comment]
This is addressed
