### ISSUE TITLE
Link to old userguides

### ISSUE THREAD

**Issue by StefMa** [gradle-guides/writing-gradle-plugins#7]
Hi guys,

I'm currently walk through the guides and found that the links in the "Next Step" section link to old guides:
<img width="465" alt="bildschirmfoto 2018-01-01 um 14 03 15" src="https://user-images.githubusercontent.com/10229883/34467856-a652fd20-eefc-11e7-9a1d-17fde4d4df38.png">
As you can see, it link to the gradle version `4.0` guide instead of the `current`.

I wanted to change it [here](https://github.com/gradle-guides/writing-gradle-plugins/blob/master/contents/index.adoc#next-steps) but I haven't found the configuration for the `{user-manual}`... 

Where can I found the setup of the `{user-manual}` so that we can link to `current` instead of `4.0`?

**Comment by bmuschko** [comment]
The Gradle version used for the guide is based on the [Wrapper version](https://github.com/gradle-guides/writing-gradle-plugins/blob/master/gradle/wrapper/gradle-wrapper.properties#L6) in the source code. Updating the Wrapper version will also change the link next the time the guide is published.

**Comment by bmuschko** [comment]
I just fixed it.

**Comment by StefMa** [comment]
Does it make sense?
I mean, why having a documentation which  pointing to another documentation
 location with another version?

I, as a consumer of the documentation, expect that it will link always to
the latest. Expect if there is something important to note for other
versions. Only then it make sense to link to an older version...

**Comment by bmuschko** [comment]
We can only provide such experience for the guides if we'd automatically ensure an upgrade to the latest version of Gradle as soon as it is released. That would potentially also mean using new APIs, remove the use of APIs that have been deprecated and so on. Right now there's no automatism to do so. In practice this is more an infrastructure problem than anything else.

The long term plan is to make the guides an integrated portion of the user manual that is released together with every new version of Gradle. Stay tuned!

**Comment by mikemac42** [comment]
I don't think updating the wrapper version actually fixed the link.  The links still point to version 4.10.3 documentation.  The first link in Next Steps is https://docs.gradle.org/4.10.3/userguide/java_gradle_plugin.html

**Comment by StefMa** [comment]
This is maybe because of this commit
https://github.com/gradle-guides/writing-gradle-plugins/commit/7b40e388b0f21d08ff3dea35091f0f2f52412717
 ?

Am Di., 26. Nov. 2019 um 16:43 Uhr schrieb Mike <notifications@github.com>:
